"""Pydantic ResearchResult schema for the four-tier territory hierarchy.

D-27: extra='forbid' on all models rejects unknown fields from LLM output.
Shape: kingdoms / duchies / condados / baronies.

The LLM GENERATES condados freely (no pre-supplied OSM list). Each condado
carries its own id, name, and centroid coordinates, plus kingdom/duchy refs.

Etapa 3 (hazy-hatching-abelson.md): MapResearchResult added — LLM returns
condados WITHOUT coords plus barony_assignments dict; legacy ResearchResult
kept for backwards compatibility until Etapa 4 migrates callers.
"""
from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, ConfigDict, ValidationError, model_validator


# Top-level keys that ResearchResult accepts. Used to sanitize LLM output that
# adds extra keys (small local models often add "regions", "historical_names",
# "cities", "description" etc. that break strict validation).
_RESEARCH_RESULT_KEYS = frozenset({"kingdoms", "duchies", "condados", "baronies"})


def parse_research_json(text: str) -> "ResearchResult":
    """Parse raw LLM JSON into ResearchResult with lenient fallback.

    1. Try strict validation (extra='forbid' as declared).
    2. If that fails, strip any top-level keys not in _RESEARCH_RESULT_KEYS
       and retry. This lets small local models (qwen2.5:7b, llama3.2:3b) that
       insist on adding metadata keys still succeed if their core structure is right.
    3. If still invalid, raise the ORIGINAL strict error (more informative than
       the second-pass error).
    """
    try:
        return ResearchResult.model_validate_json(text)
    except ValidationError as strict_err:
        try:
            data: Any = json.loads(text)
        except json.JSONDecodeError:
            raise strict_err
        if not isinstance(data, dict):
            raise strict_err
        stripped = {k: v for k, v in data.items() if k in _RESEARCH_RESULT_KEYS}
        try:
            return ResearchResult.model_validate(stripped)
        except ValidationError:
            # Surface the strict error — it tells the LLM exactly which key is wrong.
            raise strict_err


class Barony(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: str
    lon: float
    lat: float


class Duchy(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kingdom_id: str
    name: str


class Condado(BaseModel):
    """A historical county/territory generated by the LLM (not derived from OSM)."""
    model_config = ConfigDict(extra="forbid")
    id: str          # LLM-invented slug, e.g. "C_BRAGA", "C_TOLEDO"
    name: str        # Historical display name in period vernacular
    lon: float       # Centroid longitude
    lat: float       # Centroid latitude
    kingdom_id: str  # References a key in ResearchResult.kingdoms
    duchy_id: str    # References a key in ResearchResult.duchies


class ResearchResult(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kingdoms: dict[str, str]            # id -> display_name
    duchies: dict[str, Duchy]           # id -> Duchy(kingdom_id, name)
    condados: list[Condado]             # historically-generated counties with coords
    baronies: dict[str, list[Barony]]   # condado_id -> baronies


class MapCondado(BaseModel):
    """Condado as returned by the new map_research prompt — NO coords.

    Etapa 3: centroids are no longer LLM-invented; they will be computed later
    by territory_builder from member baronies (CK3-style aggregation).
    """
    model_config = ConfigDict(extra="forbid")
    id: str          # LLM-invented slug, e.g. "C_BRAGA"
    name: str        # Historical display name
    kingdom_id: str  # References a key in MapResearchResult.kingdoms
    duchy_id: str    # References a key in MapResearchResult.duchies


class MapResearchResult(BaseModel):
    """New CK3-style schema (Etapa 3) — condados without coords + barony_assignments.

    The LLM no longer invents barony lists per condado nor centroids; instead it
    assigns previously-generated baronies to condados via a flat dict mapping
    barony_id -> condado_id. A cross-reference validator enforces that every
    assignment points to a condado actually present in `condados[]`.
    """
    model_config = ConfigDict(extra="forbid")
    kingdoms: dict[str, str]                # id -> display_name
    duchies: dict[str, Duchy]               # id -> Duchy(kingdom_id, name)
    condados: list[MapCondado]              # NO coords
    barony_assignments: dict[str, str]      # barony_id -> condado_id

    @model_validator(mode="after")
    def _validate_barony_assignments_reference_existing_condados(self) -> "MapResearchResult":
        condado_ids = {c.id for c in self.condados}
        unknown = {
            bid: cid
            for bid, cid in self.barony_assignments.items()
            if cid not in condado_ids
        }
        if unknown:
            raise ValueError(
                f"barony_assignments reference unknown condado_id(s): "
                f"{sorted(set(unknown.values()))}; "
                f"known condado ids: {sorted(condado_ids)}"
            )
        return self


def validate_barony_assignments(
    result: "MapResearchResult",
    input_baronies: list[dict],
) -> None:
    """Strict cross-check between LLM assignments and the input barony list.

    Complements MapResearchResult's built-in validator (which only checks
    condado refs). This function checks the OTHER side: keys must match
    input baronies exactly. Strict mode — raises so run_with_retry re-prompts.

    Args:
        result: Validated MapResearchResult from the LLM.
        input_baronies: List of barony dicts passed to build_map_research_prompt.
                        Each has at minimum {"id": str}.

    Raises:
        ValueError: If any assignment key is not in input_baronies, or if any
                    input barony is left unassigned.
    """
    input_ids = {b["id"] for b in input_baronies}
    assigned_ids = set(result.barony_assignments.keys())

    unknown_keys = assigned_ids - input_ids
    if unknown_keys:
        raise ValueError(
            f"barony_assignments contain unknown barony id(s) not in the "
            f"input list: {sorted(unknown_keys)}; "
            f"valid input ids: {sorted(input_ids)}"
        )

    unassigned = input_ids - assigned_ids
    if unassigned:
        raise ValueError(
            f"barony_assignments are incomplete — the following input "
            f"baronies were left unassigned: {sorted(unassigned)}"
        )
