"""Pydantic ResearchResult schema for the four-tier territory hierarchy.

D-27: extra='forbid' on all models rejects unknown fields from LLM output.
Shape: kingdoms / duchies / condados / baronies.

The LLM GENERATES condados freely (no pre-supplied OSM list). Each condado
carries its own id, name, and centroid coordinates, plus kingdom/duchy refs.
"""
from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, ConfigDict, ValidationError


# Top-level keys that ResearchResult accepts. Used to sanitize LLM output that
# adds extra keys (small local models often add "regions", "historical_names",
# "cities", "description" etc. that break strict validation).
_RESEARCH_RESULT_KEYS = frozenset({"kingdoms", "duchies", "condados", "baronies"})


def parse_research_json(text: str) -> "ResearchResult":
    """Parse raw LLM JSON into ResearchResult with lenient fallback.

    1. Try strict validation (extra='forbid' as declared).
    2. If that fails, strip any top-level keys not in _RESEARCH_RESULT_KEYS
       and retry. This lets small local models (qwen2.5:7b, llama3.2:3b) that
       insist on adding metadata keys still succeed if their core structure is right.
    3. If still invalid, raise the ORIGINAL strict error (more informative than
       the second-pass error).
    """
    try:
        return ResearchResult.model_validate_json(text)
    except ValidationError as strict_err:
        try:
            data: Any = json.loads(text)
        except json.JSONDecodeError:
            raise strict_err
        if not isinstance(data, dict):
            raise strict_err
        stripped = {k: v for k, v in data.items() if k in _RESEARCH_RESULT_KEYS}
        try:
            return ResearchResult.model_validate(stripped)
        except ValidationError:
            # Surface the strict error — it tells the LLM exactly which key is wrong.
            raise strict_err


class Barony(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: str
    lon: float
    lat: float


class Duchy(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kingdom_id: str
    name: str


class Condado(BaseModel):
    """A historical county/territory generated by the LLM (not derived from OSM)."""
    model_config = ConfigDict(extra="forbid")
    id: str          # LLM-invented slug, e.g. "C_BRAGA", "C_TOLEDO"
    name: str        # Historical display name in period vernacular
    lon: float       # Centroid longitude
    lat: float       # Centroid latitude
    kingdom_id: str  # References a key in ResearchResult.kingdoms
    duchy_id: str    # References a key in ResearchResult.duchies


class ResearchResult(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kingdoms: dict[str, str]            # id -> display_name
    duchies: dict[str, Duchy]           # id -> Duchy(kingdom_id, name)
    condados: list[Condado]             # historically-generated counties with coords
    baronies: dict[str, list[Barony]]   # condado_id -> baronies
