"""SC-4-France: France 1066 toy region passes the Phase 06 export gate.

Toy region: synthetic dataset, autogenerated condados/baronies.
Parity to Reconquista NOT required (CONTEXT.md SC-3 boundary). The gate
asserts the contract: every condado has original_idx, no ocean leaks,
no color collisions, no <200px territories, all pixel_centers in bounds.
"""
from __future__ import annotations

from dataclasses import replace
from pathlib import Path

import pytest

from medieval_forge.services.export import validate_export
from medieval_forge.services.pipeline import run_pipeline
from medieval_forge.services.pipeline.region_loader import (
    clear_region_cache,
    load_region,
)

pytestmark = pytest.mark.e2e


@pytest.fixture(scope="module")
def france_output(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Run France pipeline once per module -- cheap (~5s)."""
    out = tmp_path_factory.mktemp("france_e2e_gate")
    clear_region_cache()
    cfg = replace(load_region("france_1066"), output_dir=str(out))
    run_pipeline(cfg)
    return out


def test_france_1066_passes_export_gate(france_output: Path) -> None:
    cfg = load_region("france_1066")
    report, sha256_by_file = validate_export(france_output, cfg)

    if not report.passed:
        error_summary = "\n".join(
            f"  - [{e.code}] {e.file or '-'}: {e.message}" for e in report.errors
        )
        pytest.fail(
            f"France 1066 FAILED Phase 06 export gate ({len(report.errors)} errors):\n"
            f"{error_summary}\n"
            f"Toy region geometry is autogen; if it fails the gate, fix "
            f"_autogen_territories in region_loader.py -- not the gate."
        )

    assert report.passed is True
    assert report.errors == []
    assert len(sha256_by_file) >= 10
