/**
 * Phase 08.2 Plan 04 — BEZ-CONV-05: Bézier edit reaches colored map (Wave 2).
 *
 * ANTI-PATTERN GUARD (non-negotiable):
 * The convergence CLAIM must NOT call __forgeBezierTriggerDrag or ANY __forgeBezierTrigger*
 * action hook. The drag flows through REAL page.mouse events only.
 *
 * Permitted read-only hooks (setup/inspection, NOT triggers):
 *   __forgeSelectBarony       — selection setup (not the claim)
 *   __forgeStageScale         — read-only scale inspection
 *   __forgeBezierState        — read-only Bézier state inspection (anchorCount, editLogLength,
 *                               firstAnchor, editedContourPointCount, editedRingSnapshot)
 *   __forgePanToFirstAnchor   — display-only pan, no store write
 *
 * // COASTLINE barony: "Gijón" — interior shared edges gap by construction — RESEARCH A3
 * Gijón is on the north coast of Iberia (lat ~43.54, lon ~-5.66). It has open sea boundary
 * on the north — no interior shared edges to gap when only one barony ring is re-rasterised.
 * This satisfies RESEARCH A3 (interior gaps are structural; UAT targets coastline only).
 *
 * Convergence chain (RESEARCH §454-468):
 *   Apply → snapshot POST → postRender → on success _render_producer bumps project.updated_at
 *   → cacheVersion changes → all 5 useCanvasArtifacts queries (incl. baroniesQ) refetch
 *   → BaronyLayer re-renders. baronies.geojson is regenerated by pipeline stage 15 (canvas
 *   sidecars), so the barony ring in baronies.geojson WILL differ after a successful render.
 *
 * Assertions:
 *   (1) Overlay absent before first edit; present after first drag.
 *   (2) After Apply: baronies.geojson ring for Gijón changes AND overlay clears.
 *   (3) Reload page: boundary persists (ring matches post-Apply).
 *   (4) Export ZIP: lookup_barony.png SHA-256 differs from pre-edit baseline.
 *
 * Data-testid anchors (UI-SPEC §10):
 *   bezier-apply-edits-btn     — "Apply edits" button (manual mode trigger)
 *   bezier-apply-auto-switch   — auto-immediate mode toggle
 *   bezier-edited-contour      — the amber-dashed live overlay element
 *
 * REQ-IDs: BEZ-CONV-05
 */
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { test, expect, type Page } from '@playwright/test'

// ─── Project info helper ──────────────────────────────────────────────────────

function loadProjectInfo(): { project_id: string; name: string } {
  const p = process.env.UAT_PROJECT_INFO_PATH
  if (!p) {
    throw new Error(
      'UAT_PROJECT_INFO_PATH is not set; globalSetup did not run. Did you launch via `npx playwright test`?',
    )
  }
  return JSON.parse(readFileSync(p, 'utf-8'))
}

// ─── BEZ-CONV-05 state types ─────────────────────────────────────────────────

interface BezierState {
  anchorCount: number
  activeAnchorIdx: number | null
  dirtySegmentCount: number
  editLogLength: number
  firstAnchor: { idx: number; x: number; y: number } | null
  midCurvePoint?: { x: number; y: number } | null
  /** additive (Plan 08.1 Plan 08): number of numbers in editedRingPts (2 × vertex count) */
  editedContourPointCount?: number
  /** additive (Plan 08.1 Plan 08): JSON.stringify(editedRingPts) snapshot for change detection */
  editedRingSnapshot?: string
}

async function readBezierState(page: Page): Promise<BezierState | null> {
  return page.evaluate(() => {
    const fn = (window as unknown as { __forgeBezierState?: () => unknown }).__forgeBezierState
    return fn ? (fn() as BezierState) : null
  })
}

// ─── Coastline barony selection helper ───────────────────────────────────────

// COASTLINE barony: "Gijón" — interior shared edges gap by construction — RESEARCH A3
const COASTLINE_BARONY = 'Gijón'

/**
 * Discover the barony id for a named barony from seeded baronies.geojson.
 * Name-based lookup (NOT proximity-based — Gijón is north coast, not map center).
 */
async function discoverBaronyByName(page: Page, projectId: string, name: string): Promise<string> {
  const id = await page.evaluate(
    async ([pid, targetName]: [string, string]) => {
      const res = await fetch(`/api/v3/projects/${pid}/artifacts/baronies.geojson`)
      if (!res.ok) return null
      const fc = await res.json()
      for (const feat of fc.features ?? []) {
        const fname: string | null =
          feat?.properties?.name ?? feat?.id ?? feat?.properties?.id ?? null
        if (fname && fname.trim() === targetName.trim()) {
          return (feat?.id ?? feat?.properties?.id ?? feat?.properties?.name) as string
        }
      }
      return null
    },
    [projectId, name] as [string, string],
  )
  if (!id) {
    throw new Error(
      `Barony '${name}' not found in seeded baronies.geojson — check territory_data_v3.py entry`,
    )
  }
  return id
}

// ─── Barony ring snapshot helper ─────────────────────────────────────────────

/**
 * Fetch the baronies.geojson ring for a named barony.
 * Returns the JSON-serialised coordinates array as a stable string.
 * Used to assert geometry change after a render cascade.
 */
async function fetchBaronyRing(page: Page, projectId: string, name: string): Promise<string> {
  const ring = await page.evaluate(
    async ([pid, targetName]: [string, string]) => {
      // cache: 'no-store' bypasses the browser cache (artifacts use max-age=31536000 immutable;
      // without this, the fetch returns the cached pre-render version even after _render_producer
      // regenerates baronies.geojson). Append timestamp as fallback for non-standard fetch impls.
      const url = `/api/v3/projects/${pid}/artifacts/baronies.geojson?_nc=${Date.now()}`
      const res = await fetch(url, { cache: 'no-store' })
      if (!res.ok) return null
      const fc = await res.json()
      for (const feat of fc.features ?? []) {
        const fname: string | null = feat?.properties?.name ?? null
        if (fname && fname.trim() === targetName.trim()) {
          return JSON.stringify(feat.geometry?.coordinates)
        }
      }
      return null
    },
    [projectId, name] as [string, string],
  )
  if (!ring) throw new Error(`Could not fetch barony ring for '${name}'`)
  return ring
}

// ─── lookup_barony.png SHA-256 helper ────────────────────────────────────────

/** Fetch lookup_barony.png through the running app and return its SHA-256 hex digest. */
async function lookupBaronySha(page: Page, projectId: string): Promise<string> {
  const b64 = await page.evaluate(async (pid) => {
    // cache: 'no-store' bypasses immutable HTTP cache (artifacts use max-age=31536000)
    const url = `/api/v3/projects/${pid}/artifacts/lookup_barony.png?_nc=${Date.now()}`
    const res = await fetch(url, { cache: 'no-store' })
    if (!res.ok) throw new Error(`artifact fetch failed: ${res.status}`)
    const buf = new Uint8Array(await res.arrayBuffer())
    let binary = ''
    for (let i = 0; i < buf.length; i++) binary += String.fromCharCode(buf[i])
    return btoa(binary)
  }, projectId)
  return createHash('sha256').update(Buffer.from(b64, 'base64')).digest('hex')
}

// ─── Canvas navigation helpers ────────────────────────────────────────────────

async function navigateToWorkspace(page: Page, projectId: string) {
  await page.goto(`/projects/${projectId}`)
  await expect(page.getByTestId('canvas-stage')).toBeVisible({ timeout: 20_000 })
  await expect(page.getByTestId('territory-layer-ready')).toBeAttached({ timeout: 30_000 })
}

/**
 * Zoom in using REAL wheel events until __forgeStageScale crosses targetAbsolute.
 */
async function zoomInUntilAbsolute(
  page: Page,
  cx: number,
  cy: number,
  targetAbsolute: number,
  maxTicks = 80,
): Promise<number> {
  await page.mouse.move(cx, cy)
  await page.waitForTimeout(50)
  let ticks = 0
  while (ticks < maxTicks) {
    const scale = await page.evaluate(
      () => (window as unknown as { __forgeStageScale?: number }).__forgeStageScale ?? 1,
    )
    if (scale >= targetAbsolute) break
    await page.mouse.move(cx, cy)
    await page.mouse.wheel(0, -100)
    ticks++
  }
  return await page.evaluate(
    () => (window as unknown as { __forgeStageScale?: number }).__forgeStageScale ?? 1,
  )
}

/**
 * Full setup: navigate, enter V tool, select Gijón coastline barony, zoom 6×, pan to anchor.
 * Returns firstAnchor screen coords and canvasBox for caller.
 */
async function setupCoastlineBarony(page: Page, projectId: string) {
  await navigateToWorkspace(page, projectId)
  await expect(page.getByTestId('edit-tool-palette')).toBeVisible()
  await page.getByTestId('edit-tool-v').click()

  const baronyId = await discoverBaronyByName(page, projectId, COASTLINE_BARONY)
  await page.evaluate((id) => {
    ;(window as unknown as { __forgeSelectBarony?: (id: string) => void }).__forgeSelectBarony?.(id)
  }, baronyId)

  await expect
    .poll(async () => (await readBezierState(page))?.anchorCount ?? 0, { timeout: 15_000 })
    .toBeGreaterThanOrEqual(4)

  const fitScale = await page.evaluate(
    () => (window as unknown as { __forgeStageScale?: number }).__forgeStageScale ?? 1,
  )

  const canvasBox = await page.getByTestId('canvas-stage').boundingBox()
  expect(canvasBox, 'canvas-stage bounding box must be present').not.toBeNull()

  const canvasCx = canvasBox!.x + canvasBox!.width / 2
  const canvasCy = canvasBox!.y + canvasBox!.height / 2

  const targetScale = fitScale * 6
  await zoomInUntilAbsolute(page, canvasCx, canvasCy, targetScale, 80)

  const panned = await page.evaluate(
    () =>
      (
        window as unknown as { __forgePanToFirstAnchor?: () => boolean }
      ).__forgePanToFirstAnchor?.() ?? false,
  )
  expect(panned, '__forgePanToFirstAnchor must succeed').toBe(true)

  const stateAfterZoom = await readBezierState(page)
  expect(stateAfterZoom?.firstAnchor, 'firstAnchor must be non-null after zoom').not.toBeNull()

  return { baronyId, canvasBox: canvasBox!, stateAfterZoom: stateAfterZoom! }
}

// ─── BEZ-CONV-05: Bézier convergence end-to-end ──────────────────────────────

test.describe('Phase 08.2 — BEZ-CONV-05: Bézier edit reaches colored map', () => {
  /**
   * Wave 2 (Plan 04): un-skipped. Full convergence criterion for G8 closure.
   * A real-mouse drag on the Gijón coastline barony, followed by "Aplicar edições",
   * must: (a) change the colored barony boundary, (b) clear the amber overlay,
   * (c) survive a page reload, (d) appear in the 12-file export.
   */

  // ── Test 1: Overlay lifecycle ─────────────────────────────────────────────

  test(
    'coastline: overlay absent before first edit AND present after first drag',
    async ({ page }: { page: Page }) => {
      // ANTI-PATTERN GUARD: the drag is a real page.mouse event.
      // __forgeBezierState / __forgeSelectBarony / __forgePanToFirstAnchor are read-only.
      // No __forgeBezierTrigger* is called anywhere.

      const info = loadProjectInfo()
      const { stateAfterZoom } = await setupCoastlineBarony(page, info.project_id)

      // Assert BEFORE first drag: overlay absent (editLog empty → Plan 03 guard hides overlay)
      // NOTE: bezier-edited-contour is a Konva <Line> rendered on canvas — not a DOM element.
      // The Plan 03 overlay guard is: editedRingPts.length >= 6 && editLog.length > 0.
      // editedContourPointCount is always > 0 when a barony is selected (it reports ring size).
      // The correct absence check is editLogLength === 0 (the guard condition).
      const stateBefore = await readBezierState(page)
      expect(
        stateBefore?.editLogLength ?? 0,
        'overlay must be absent before first drag (editLog empty, Plan 03 guard)',
      ).toBe(0)

      const editLog0 = stateAfterZoom.editLogLength
      const { x: ax, y: ay } = stateAfterZoom.firstAnchor!

      // REAL page.mouse drag on firstAnchor
      await page.mouse.move(ax, ay)
      await page.mouse.down()
      await page.mouse.move(ax + 30, ay + 30, { steps: 8 })
      await page.mouse.up()

      // Wait for op:'move' to commit (editLog grows)
      await expect
        .poll(async () => (await readBezierState(page))?.editLogLength ?? editLog0, {
          timeout: 8_000,
        })
        .toBeGreaterThan(editLog0)

      // Assert AFTER first drag: overlay present (editLog > 0 → Plan 03 guard shows overlay)
      // The editLogLength already grew (asserted above). Confirm it's still > 0 here.
      // (editedContourPointCount is always > 0 when a barony is selected; the guard is editLog.)
      const stateAfterDrag = await readBezierState(page)
      expect(
        stateAfterDrag?.editLogLength ?? 0,
        'overlay must be present after first drag (editLog > 0, Plan 03 guard)',
      ).toBeGreaterThan(0)

      // Apply button must be enabled (editLog > 0) — real DOM button, Playwright-accessible
      await expect(page.getByTestId('bezier-apply-edits-btn')).toBeEnabled({ timeout: 5_000 })
    },
  )

  // ── Test 2: Apply triggers convergence ───────────────────────────────────

  test(
    'coastline: after Apply, colored barony boundary pixels change AND overlay clears (END-TO-END)',
    async ({ page }: { page: Page }) => {
      // ANTI-PATTERN GUARD: the drag is a real page.mouse event.
      // __forgeBezierState is read-only state inspection, never a trigger.

      test.setTimeout(240_000) // full pipeline render (251 baronies) takes ~90-120s on first run

      const info = loadProjectInfo()
      const { stateAfterZoom } = await setupCoastlineBarony(page, info.project_id)

      // Capture the baronies.geojson ring BEFORE the edit
      const ringBefore = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
      expect(ringBefore).toBeTruthy()

      const editLog0 = stateAfterZoom.editLogLength
      const { x: ax, y: ay } = stateAfterZoom.firstAnchor!

      // REAL page.mouse drag on firstAnchor
      await page.mouse.move(ax, ay)
      await page.mouse.down()
      await page.mouse.move(ax + 30, ay + 30, { steps: 8 })
      await page.mouse.up()

      // Wait for op:'move' to commit
      await expect
        .poll(async () => (await readBezierState(page))?.editLogLength ?? editLog0, {
          timeout: 8_000,
        })
        .toBeGreaterThan(editLog0)

      // Overlay must be present before Apply: editLogLength > editLog0 (drag committed)
      // The guard on the Konva <Line> is editLog.length > 0; we verify via editLogLength.
      const stateBeforeApply = await readBezierState(page)
      expect(
        stateBeforeApply?.editLogLength ?? 0,
        'editLog must be non-empty before Apply (drag committed op:move)',
      ).toBeGreaterThan(editLog0)

      // Click "Aplicar edições" — triggers snapshot POST + postRender
      await page.getByTestId('bezier-apply-edits-btn').click()

      // Wait for the render cascade to complete:
      // _render_producer bumps project.updated_at on success → cacheVersion changes
      // → all 5 useCanvasArtifacts queries refetch → baroniesQ returns new ring
      // The overlay guard (editLog cleared on rendering→generated) then hides the overlay.
      await expect
        .poll(
          async () => {
            const ring = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
            return ring !== ringBefore
          },
          {
            timeout: 180_000, // full pipeline render (251 baronies) can take 90-120s on first run
            intervals: [3_000, 5_000, 8_000],
            message: 'baronies.geojson ring for Gijón must change after Apply+render cascade',
          },
        )
        .toBe(true)

      // THE LOAD-BEARING ASSERTION: colored barony boundary AFTER differs from BEFORE
      const ringAfter = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
      expect(
        ringAfter,
        'END-TO-END: colored barony boundary after Apply+render must differ from pre-edit ring',
      ).not.toBe(ringBefore)

      // Overlay must have cleared (clear-on-converge: editLog reset → Plan 03 guard hides).
      // The guard is editLog.length > 0; useBezierApply clears editLog when it observes the
      // RunStore rendering→generated transition via useRunStore.subscribe.
      //
      // The ring changed (load-bearing assertion above passed), meaning the render completed
      // and project.updated_at was bumped. The cacheVersion refetch is what caused the ring
      // to change in our poll. At this point the RunStore should be in 'generated' state
      // and the subscribe callback should have fired to clear editLog.
      //
      // Allow 45s: SSE stream delivery + React re-render + subscribe callback.
      await expect
        .poll(async () => (await readBezierState(page))?.editLogLength ?? -1, {
          timeout: 45_000,
          intervals: [1_000, 2_000, 3_000],
        })
        .toBe(0)
    },
  )

  // ── Test 3: Reload persistence ───────────────────────────────────────────

  test(
    'coastline: after Apply + reload, boundary persists (edit survives page reload)',
    async ({ page }: { page: Page }) => {
      test.setTimeout(360_000) // full pipeline render (~120s) + reload

      const info = loadProjectInfo()
      const { stateAfterZoom } = await setupCoastlineBarony(page, info.project_id)

      const ringBefore = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
      const editLog0 = stateAfterZoom.editLogLength
      const { x: ax, y: ay } = stateAfterZoom.firstAnchor!

      // REAL page.mouse drag
      await page.mouse.move(ax, ay)
      await page.mouse.down()
      await page.mouse.move(ax + 30, ay + 30, { steps: 8 })
      await page.mouse.up()

      await expect
        .poll(async () => (await readBezierState(page))?.editLogLength ?? editLog0, {
          timeout: 8_000,
        })
        .toBeGreaterThan(editLog0)

      // Click Apply and wait for convergence
      await page.getByTestId('bezier-apply-edits-btn').click()
      await expect
        .poll(
          async () => {
            const ring = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
            return ring !== ringBefore
          },
          { timeout: 180_000, intervals: [3_000, 5_000, 8_000] },
        )
        .toBe(true)

      // Record the ring after Apply
      const ringAfterApply = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
      expect(ringAfterApply).not.toBe(ringBefore)

      // Reload the page
      await page.reload()
      await expect(page.getByTestId('canvas-stage')).toBeVisible({ timeout: 20_000 })
      await expect(page.getByTestId('territory-layer-ready')).toBeAttached({ timeout: 30_000 })

      // Assert boundary PERSISTS after reload (stored in DB branch, reloaded from artifacts)
      const ringAfterReload = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
      expect(
        ringAfterReload,
        'SURVIVES RELOAD: barony ring after page reload must match ring after Apply',
      ).toBe(ringAfterApply)
    },
  )

  // ── Test 4: Export contains changed lookup ────────────────────────────────

  test(
    'coastline: after Apply, lookup_barony.png in export differs from pre-edit baseline',
    async ({ page }: { page: Page }) => {
      test.setTimeout(360_000) // full pipeline render (~120s) + export pipeline

      const info = loadProjectInfo()
      const { stateAfterZoom } = await setupCoastlineBarony(page, info.project_id)

      // Capture pre-edit lookup_barony.png SHA-256
      const baselineSha = await lookupBaronySha(page, info.project_id)
      expect(baselineSha).toMatch(/^[0-9a-f]{64}$/)

      const ringBefore = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
      const editLog0 = stateAfterZoom.editLogLength
      const { x: ax, y: ay } = stateAfterZoom.firstAnchor!

      // REAL page.mouse drag
      await page.mouse.move(ax, ay)
      await page.mouse.down()
      await page.mouse.move(ax + 30, ay + 30, { steps: 8 })
      await page.mouse.up()

      await expect
        .poll(async () => (await readBezierState(page))?.editLogLength ?? editLog0, {
          timeout: 8_000,
        })
        .toBeGreaterThan(editLog0)

      // Click Apply and wait for render cascade
      await page.getByTestId('bezier-apply-edits-btn').click()
      await expect
        .poll(
          async () => {
            const ring = await fetchBaronyRing(page, info.project_id, COASTLINE_BARONY)
            return ring !== ringBefore
          },
          { timeout: 180_000, intervals: [3_000, 5_000, 8_000] },
        )
        .toBe(true)

      // Trigger export and re-fetch lookup_barony.png SHA-256
      const exportStatus = await page.evaluate(async (pid) => {
        const res = await fetch(`/api/v3/projects/${pid}/export`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({}),
        })
        return res.status
      }, info.project_id)
      expect([200, 201]).toContain(exportStatus)

      const afterSha = await lookupBaronySha(page, info.project_id)

      // APPEARS IN EXPORT: lookup_barony.png SHA-256 must differ from pre-edit baseline
      expect(
        afterSha,
        'APPEARS IN EXPORT: lookup_barony.png after Apply+export must differ from pre-edit baseline',
      ).not.toBe(baselineSha)
    },
  )
})
